const prisma = require("../utils/prisma");
const { analyzeCourseLink } = require("../services/courseAnalyzer");

exports.addCourse = async (req, res) => {
  try {
    const { title, link, category, description, difficulty, thumbnail } = req.body;

    if (!title || !link || !category) {
      return res.status(400).json({ msg: "Title, link, and category are required" });
    }

    const user = await prisma.user.findUnique({
      where: { id: req.user.userId },
      select: { role: true },
    });

    if (user?.role !== "TEACHER") {
      return res.status(403).json({ msg: "Only teachers can create courses" });
    }

    const course = await prisma.course.create({
      data: {
        title,
        link,
        category,
        description,
        difficulty: difficulty || "BEGINNER",
        thumbnail,
        teacherId: req.user.userId,
      },
    });

    let analysis = { lessons: [], quiz: null, source: "none" };

    try {
      analysis = await analyzeCourseLink({ title, description, category, link });

      if (analysis.lessons?.length) {
        await prisma.courseLesson.createMany({
          data: analysis.lessons.map((lesson) => ({
            courseId: course.id,
            order: lesson.order,
            title: lesson.title,
            videoUrl: lesson.videoUrl,
            duration: lesson.duration,
          })),
        });
      }

      if (analysis.quiz?.questions?.length) {
        await prisma.quiz.create({
          data: {
            title: analysis.quiz.title,
            description: analysis.quiz.description,
            questions: JSON.stringify(analysis.quiz.questions),
            answers: JSON.stringify(analysis.quiz.answers),
            creatorId: req.user.userId,
            courseId: course.id,
            autoGenerated: true,
          },
        });
      }
    } catch (analysisErr) {
      console.log("Course analysis error:", analysisErr);
    }

    const fullCourse = await prisma.course.findUnique({
      where: { id: course.id },
      include: {
        lessons: { orderBy: { order: "asc" } },
        quizzes: { select: { id: true, title: true, description: true, autoGenerated: true } },
      },
    });

    res.status(201).json({
      ...fullCourse,
      analysisSource: analysis.source,
      lessonCount: fullCourse.lessons.length,
    });
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

exports.getCourses = async (req, res) => {
  try {
    const { category, difficulty, search, sort } = req.query;

    const filters = {};
    if (category && category !== 'All') filters.category = category;
    if (difficulty && difficulty !== 'All') filters.difficulty = difficulty;

    if (search) {
      filters.OR = [
        { title: { contains: search } },
        { description: { contains: search } },
      ];
    }

    let orderBy = { createdAt: 'desc' };
    if (sort === 'popular') {
      orderBy = { views: 'desc' };
    } else if (sort === 'rating') {
      // Since sorting by dynamic average rating isn't simple in raw MongoDB Prisma queries,
      // we order by views (popularity indicator) as a high-quality fallback.
      orderBy = { views: 'desc' };
    }

    const courses = await prisma.course.findMany({
      where: filters,
      include: {
        teacher: {
          select: {
            id: true,
            name: true,
            username: true,
            avatar: true,
            bio: true,
          }
        },
        _count: {
          select: { enrollments: true, reviews: true }
        }
      },
      orderBy
    });

    res.json(courses);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

exports.getCourseById = async (req, res) => {
  try {
    const { id } = req.params;

    const course = await prisma.course.findUnique({
      where: { id },
      include: {
        teacher: {
          select: {
            id: true,
            name: true,
            username: true,
            avatar: true,
            bio: true,
          },
        },
        lessons: { orderBy: { order: "asc" } },
        quizzes: {
          select: {
            id: true,
            title: true,
            description: true,
            autoGenerated: true,
          },
        },
        reviews: {
          include: {
            student: {
              select: {
                id: true,
                name: true,
                avatar: true,
              },
            },
          },
        },
        enrollments: {
          select: { studentId: true },
        },
      },
    });

    if (!course) {
      return res.status(404).json({ msg: "Course not found" });
    }

    let shouldCountView = false;

    if (req.user?.userId) {
      const viewer = await prisma.user.findUnique({
        where: { id: req.user.userId },
        select: { id: true, role: true },
      });

      const isOwner = course.teacherId === viewer?.id;

      if (!isOwner) {
        const existingView = await prisma.courseView.findUnique({
          where: {
            userId_courseId: {
              userId: req.user.userId,
              courseId: id,
            },
          },
        });

        if (!existingView) {
          await prisma.courseView.create({
            data: { userId: req.user.userId, courseId: id },
          });
          shouldCountView = true;
        }
      }
    }

    if (shouldCountView) {
      await prisma.course.update({
        where: { id },
        data: { views: { increment: 1 } },
      });
      course.views += 1;
    }

    res.json(course);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

exports.getTeacherCourses = async (req, res) => {
  try {
    const courses = await prisma.course.findMany({
      where: { teacherId: req.user.userId },
      include: {
        enrollments: true,
        reviews: true,
        _count: {
          select: { enrollments: true, reviews: true }
        }
      },
      orderBy: { createdAt: 'desc' }
    });

    res.json(courses);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

exports.updateCourse = async (req, res) => {
  try {
    const { id } = req.params;
    const { title, description, link, category, difficulty, thumbnail } = req.body;

    const course = await prisma.course.findUnique({
      where: { id }
    });

    if (!course) {
      return res.status(404).json({ msg: "Course not found" });
    }

    if (course.teacherId !== req.user.userId) {
      return res.status(403).json({ msg: "Not authorized to update this course" });
    }

    const updated = await prisma.course.update({
      where: { id },
      data: {
        ...(title && { title }),
        ...(description && { description }),
        ...(link && { link }),
        ...(category && { category }),
        ...(difficulty && { difficulty }),
        ...(thumbnail && { thumbnail }),
      }
    });

    res.json(updated);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

exports.deleteCourse = async (req, res) => {
  try {
    const { id } = req.params;

    const course = await prisma.course.findUnique({
      where: { id }
    });

    if (!course) {
      return res.status(404).json({ msg: "Course not found" });
    }

    if (course.teacherId !== req.user.userId) {
      return res.status(403).json({ msg: "Not authorized to delete this course" });
    }

    await prisma.course.delete({
      where: { id }
    });

    res.json({ msg: "Course deleted successfully" });
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

exports.getRecommendations = async (req, res) => {
  try {
    const userId = req.user.userId;

    // Find user's enrolled courses to extract interested categories
    const enrollments = await prisma.enrollment.findMany({
      where: { studentId: userId },
      include: { course: true }
    });

    const enrolledCourseIds = enrollments.map(e => e.courseId);
    const interestedCategories = [...new Set(enrollments.map(e => e.course?.category).filter(Boolean))];

    let recommendedCourses = [];

    if (interestedCategories.length > 0) {
      recommendedCourses = await prisma.course.findMany({
        where: {
          category: { in: interestedCategories },
          id: { notIn: enrolledCourseIds }
        },
        include: {
          teacher: {
            select: { id: true, name: true, username: true, avatar: true }
          },
          _count: { select: { enrollments: true, reviews: true } }
        },
        orderBy: [
          { views: 'desc' },
          { createdAt: 'desc' }
        ],
        take: 6
      });
    }

    // Fallback to trending courses if recommendations are few
    if (recommendedCourses.length < 3) {
      const remainingCount = 6 - recommendedCourses.length;
      const recommendedIds = recommendedCourses.map(c => c.id);

      const trending = await prisma.course.findMany({
        where: {
          id: {
            notIn: [...enrolledCourseIds, ...recommendedIds]
          }
        },
        include: {
          teacher: {
            select: { id: true, name: true, username: true, avatar: true }
          },
          _count: { select: { enrollments: true, reviews: true } }
        },
        orderBy: [
          { views: 'desc' }
        ],
        take: remainingCount
      });

      recommendedCourses = [...recommendedCourses, ...trending];
    }

    res.json(recommendedCourses);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

exports.getTrendingCourses = async (req, res) => {
  try {
    const trending = await prisma.course.findMany({
      include: {
        teacher: {
          select: { id: true, name: true, username: true, avatar: true }
        },
        _count: { select: { enrollments: true, reviews: true } }
      },
      orderBy: [
        { views: 'desc' }
      ],
      take: 6
    });
    res.json(trending);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

exports.getSimilarCourses = async (req, res) => {
  try {
    const { id } = req.params;
    const course = await prisma.course.findUnique({ where: { id } });
    if (!course) {
      return res.status(404).json({ msg: "Course not found" });
    }

    const similar = await prisma.course.findMany({
      where: {
        category: course.category,
        id: { not: id }
      },
      include: {
        teacher: {
          select: { id: true, name: true, username: true, avatar: true }
        },
        _count: { select: { enrollments: true, reviews: true } }
      },
      orderBy: { views: 'desc' },
      take: 4
    });

    res.json(similar);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

exports.getSearchSuggestions = async (req, res) => {
  try {
    const { q } = req.query;
    if (!q) return res.json([]);

    const suggestions = await prisma.course.findMany({
      where: {
        OR: [
          { title: { contains: q } },
          { category: { contains: q } },
        ],
      },
      select: {
        id: true,
        title: true,
        category: true
      },
      take: 5
    });

    res.json(suggestions);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};