const prisma = require("../utils/prisma");

// Create a quiz
exports.createQuiz = async (req, res) => {
  try {
    const { title, description, questions, answers } = req.body;

    if (!title || !questions || !answers) {
      return res.status(400).json({ msg: "Title, questions, and answers are required" });
    }

    const quiz = await prisma.quiz.create({
      data: {
        title,
        description,
        questions: JSON.stringify(questions),
        answers: JSON.stringify(answers),
        creatorId: req.user.userId
      }
    });

    res.status(201).json(quiz);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

// Get all quizzes
exports.getAllQuizzes = async (req, res) => {
  try {
    const quizzes = await prisma.quiz.findMany({
      include: {
        creator: {
          select: { name: true, username: true }
        }
      },
      orderBy: { createdAt: 'desc' }
    });

    // Parse JSON strings back to arrays
    const parsedQuizzes = quizzes.map(q => ({
      ...q,
      questions: JSON.parse(q.questions)
    }));

    res.json(parsedQuizzes);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

// Get quiz linked to a course (no answers exposed)
exports.getQuizByCourse = async (req, res) => {
  try {
    const { courseId } = req.params;

    const quiz = await prisma.quiz.findFirst({
      where: { courseId },
      orderBy: { createdAt: "desc" },
      include: {
        creator: { select: { name: true, username: true } },
      },
    });

    if (!quiz) {
      return res.status(404).json({ msg: "No quiz for this course" });
    }

    res.json({
      id: quiz.id,
      title: quiz.title,
      description: quiz.description,
      autoGenerated: quiz.autoGenerated,
      courseId: quiz.courseId,
      questions: JSON.parse(quiz.questions),
      creator: quiz.creator,
    });
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

// Get quiz by ID
exports.getQuizById = async (req, res) => {
  try {
    const { id } = req.params;

    const quiz = await prisma.quiz.findUnique({
      where: { id },
      include: {
        creator: {
          select: { name: true, username: true }
        }
      }
    });

    if (!quiz) {
      return res.status(404).json({ msg: "Quiz not found" });
    }

    const parsedQuiz = {
      ...quiz,
      questions: JSON.parse(quiz.questions),
      answers: JSON.parse(quiz.answers)
    };

    res.json(parsedQuiz);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

// Submit quiz answers
exports.submitQuiz = async (req, res) => {
  try {
    const { id } = req.params;
    const { userAnswers } = req.body;

    const quiz = await prisma.quiz.findUnique({
      where: { id }
    });

    if (!quiz) {
      return res.status(404).json({ msg: "Quiz not found" });
    }

    const correctAnswers = JSON.parse(quiz.answers);
    let score = 0;

    userAnswers.forEach((answer, index) => {
      if (answer === correctAnswers[index]) {
        score++;
      }
    });

    const result = {
      totalQuestions: correctAnswers.length,
      score,
      percentage: parseFloat(((score / correctAnswers.length) * 100).toFixed(2))
    };

    await prisma.quizAttempt.create({
      data: {
        userId: req.user.userId,
        quizId: id,
        score: result.score,
        totalQuestions: result.totalQuestions,
        percentage: result.percentage
      }
    });

    // Trigger achievement notification and record reward if they got 100%
    if (result.percentage === 100) {
      try {
        await prisma.reward.create({
          data: {
            userId: req.user.userId,
            type: "BADGE",
            badge: `Master of ${quiz.title}`,
            points: 50
          }
        });

        await prisma.notification.create({
          data: {
            userId: req.user.userId,
            message: `Achievement Unlocked! You earned the "Master of ${quiz.title}" badge!`,
            type: "ACHIEVEMENT"
          }
        });
      } catch (err) {
        console.log("Reward/Notification error:", err);
      }
    }

    res.json(result);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

// Get quizzes created by the logged-in teacher
exports.getTeacherQuizzes = async (req, res) => {
  try {
    const quizzes = await prisma.quiz.findMany({
      where: { creatorId: req.user.userId },
      orderBy: { createdAt: 'desc' }
    });

    const parsedQuizzes = quizzes.map(q => ({
      ...q,
      questions: JSON.parse(q.questions),
      answers: JSON.parse(q.answers)
    }));

    res.json(parsedQuizzes);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

// Get leaderboard for a specific quiz
exports.getQuizLeaderboard = async (req, res) => {
  try {
    const { id } = req.params;

    const attempts = await prisma.quizAttempt.findMany({
      where: { quizId: id },
      include: {
        user: {
          select: { id: true, name: true, username: true, avatar: true }
        }
      },
      orderBy: [{ percentage: "desc" }, { score: "desc" }, { createdAt: "asc" }],
      take: 10
    });

    res.json(attempts);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

// Get global leaderboard across all quizzes
exports.getGlobalLeaderboard = async (req, res) => {
  try {
    const attempts = await prisma.quizAttempt.findMany({
      include: {
        user: {
          select: { id: true, name: true, username: true, avatar: true }
        },
        quiz: {
          select: { id: true, title: true }
        }
      },
      orderBy: [{ percentage: "desc" }, { score: "desc" }, { createdAt: "asc" }],
      take: 20
    });

    res.json(attempts);
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

// Delete a quiz
exports.deleteQuiz = async (req, res) => {
  try {
    const { id } = req.params;

    const quiz = await prisma.quiz.findUnique({
      where: { id }
    });

    if (!quiz) {
      return res.status(404).json({ msg: "Quiz not found" });
    }

    if (quiz.creatorId !== req.user.userId) {
      return res.status(403).json({ msg: "Not authorized to delete this quiz" });
    }

    await prisma.quiz.delete({
      where: { id }
    });

    res.json({ msg: "Quiz deleted successfully" });
  } catch (err) {
    console.log("ERROR:", err);
    res.status(500).json({ msg: err.message });
  }
};

